### ISSUE TITLE
How to properly install

### ISSUE THREAD

**Issue by abonforti** [NdR91/NdR-PhoneUI#1]
Hi, would be possible to have a little more details about how to install this awesome dashboard?
Many thanks!

**Comment by NdR91** [comment]
Hello Alessio, the README is still in progress. I plan to finish it by the end of this week.

One question: do you speak Italian? Cause i was planning to write this Readme in Italian. A very good English version can be found at the link I mentioned under the screesnhots.

Let me know, maybe I can evaluate an english version too.

Thanks!

**Comment by abonforti** [comment]
Ciao, can you link the English documentation you were referring to?
By the way, yes I am Italian :)

**Comment by abonforti** [comment]
Thanks a lot for the new README, now it's definitely easier to understand!
One small question, are you sure that the alarm popup is working? Can't understand why it's referring to non-existent services while tapping on both the buttons, and can't find the configuration as well :\

**Comment by NdR91** [comment]
Ciao Alessio,

I'll work to the Readme in order to finish it. Probably next week.

Regarding the alarm: do you have the `alarm_control_panel:` integration settled up in you `configuration.yaml`?

**Comment by abonforti** [comment]
> 
> 
> Ciao Alessio,
> 
> I'll work to the Readme in order to finish it. Probably next week.
> 
> Regarding the alarm: do you have the `alarm_control_panel:` integration settled up in you `configuration.yaml`?

Ciao, awesome news!
Yes, I do have that.

**Comment by NdR91** [comment]
Post a screenshot of the error

**Comment by abonforti** [comment]
![image](https://user-images.githubusercontent.com/38355294/129451836-4cf0d085-92a7-4d21-ad35-3b02f928188e.png)

![image](https://user-images.githubusercontent.com/38355294/129451893-feb94fb9-d981-4870-9e77-91017295311f.png)

https://pastebin.com/6GptwPL0

**Comment by NdR91** [comment]
It seems you don't have a corrected setup of the Alarm component. Check the official documentation or post your Alarm configuration here.

https://www.home-assistant.io/integrations/manual

**Comment by abonforti** [comment]
Mmm looks strange since with my existing dashboard is working as per expected. Is the alarm.yaml file the only related one to this component, according to your board?

**Comment by NdR91** [comment]
Now I understood the issue. Let me check my configuration, I'll fix that soon

**Comment by abonforti** [comment]
Super! Thanks again a lot!
Another question (hopefully the last one), but maybe it's a feature request: I have some light entities which supports color chosing. Checked your templates and doesn't look you've provided that functionality. Is that confirmed? Is it in any pipeline from your perspective? Otherwise I might start working on it and in case open a PR.

**Comment by NdR91** [comment]
Finally I got it working. Please check the last release: [1.1](https://github.com/NdR91/NdR-PhoneUI/releases/tag/1.1)

> I have some light entities which supports color chosing. Checked your templates and doesn't look you've provided that functionality. Is that confirmed? Is it in any pipeline from your perspective? Otherwise I might start working on it and in case open a PR.

You're right: currently there is only the brightness adjusting. I'll see what I can do regarding the color selection :)
